---
title: The allocation mechanisms
output:
  html_document: 
    toc: yes
---


# 1. Truthful Revelation: Random Serial Dictatorship

Random serial dictatorship is a simple mechanism that probably comes first to mind to most microeconomists:

1. Each Student orders all topics from most preferred to least preferred.
2. Then the algorithm moves through all students in a purely random order. Each student gets her most preferred topic from the set of all topics that have not yet been given to a student earlier.

**Advantage:** With this algorithm, it is in the best interest for each student to order all topics according to her true preferences. It relieves students from all worries about strategizing: just state the truth.

**Drawback:** An outcome under random serial dictatorship is not neccesarily optimal if we assign numeric welfare levels to different allocations, e.g. when we would prefer allocations in which each student gets one of her top-3 ranked topics.


# 2. Minimizing A Cost Function 

The following cost minimization mechanism may appear most natural to the operations research community.

1. Each Student orders all topics from most preferred to least preferred.
2. We assign a cost to every allocated student-topic pair. Natural choices would be that the cost is the position at which the student has ranked the topic or the square of that position.
3. We now find an allocation that minimizes the sum of costs over all students.

The minimization problem in step 3 is a classic optimization problem, known as the `Linear Assignment Problem` and can for example be solved in polynomial time by the [Hungarian Algorithm](https://en.wikipedia.org/wiki/Hungarian_algorithm).

We consider 3 different cost functions. In every cost function the cost of a student-topic matching only depends on the rank at which the student has ranked that topic. The table shows the associated costs:

| Rank of Topic:  | 1 | 2 | 3 | 4    | 5    | 6     | 7     | 8     | ... |
|-----------------|---|---|---|------|------|-------|-------|-------|-----|
| Linear Cost:    | 1 | 2 | 3 | 4    | 5    | 6     | 7     | 8     | ... |
| Quadratic Cost: | 1 | 4 | 9 | 16   | 25   | 36    | 49    | 64    | ... |
| 3-5 Cost:       | 1 | 2 | 3 | 1000 | 1500 | 60000 | 70000 | 80000 | ... |

Note: The 3-5 cost rule tries to give all students a topic among their top-3 topics or, if not feasible, at least among the top-5 topics.

# Comparing Random Serial Dictatorship with Cost Minimization Algorithms

To see why cost-minimization mechanism may be preferable to random serial dictatorship, consider the following example with three students that truthfully state their preferences over three topics.

| costs | A | B | C |
|-------|---|---|---|
| Anna  | 1 | 2 | 3 |
| Bob   | 1 | 2 | 3 |
| Carla | 1 | 3 | 2 |


Anna and Bob share the preference ordering `A, B, C` over the three topics. Carla's preferences `A, C, B` just differ by prefering C over B. The table shows the cost for each student-topic match. Here, the decision maker specified that the cost of a match is equal to the position of the topic in the student's ranking.

If we want to minimize the total cost, it is optimal to always give topic C to Carla and give topics A and B to Anna and Bob. Total cost would then be 

1.5+1.5+2=5

In contrast, with the random serial dictatorship Carla also gets topic A with probability 1/3, in which case Anna or Bob get their least desired topic C.  Expected total cost would then be higher:

1/3 ((1+2+2.5)+(1+2+2.5)+(1+2+2)) = 5,33

Does this mean that is always optimal to use the cost minimization mechanism if want to minimize a specific cost function? Not neccessarily.

Assume that Carla actually prefers a lottery in which she gets A, C and B each with probability 1/3 than getting her second choice C for sure. Then in the cost-minimization mechanism Carla would benefit from misrepresenting her preferences in our example and state the preference order 'A,B,C'. Since then all students stated the same preferences, the cost minimization mechanism cannot do better than to assign each topic to each student with probability 1/3. Expected cost under the misrepresented preferences would then be 

2+2+2=6.

We would then have a worse outcome than under random serial dictatorship where it is optimal to state preferences truthfully.

So which mechanism is better? There is no clear answer. It depends.
