#. serialdict
##. label
Random Serial Dictatorship
##. desc
A classic and simple incentive compatible algorithm. Students order all topics according to their preferences.

Students choose their topics in order of randomly given priorities. Each student picks her most favorite topic from all topics that have not yet been taken by a student with higher priority. 

### Advantages:
  - It is incentive compatible for students to rank topics according to their true preferences. Students don't have to strategize.
  - Easy to explain and to understand.

### Disadvantages:
  - There is no way for students to express their cardinal preferences. Outcomes can be dominated by algorithms that allow to strategize but allow more effective risk allocation among students.
  - Students have to rank all seminars.

#. serialdict_safe
##. label
Serial Dictatorship or 
##. desc
A simple incentive compatible algorithm. Students order all topics according to their preferences.

Students choose their topics in order of randomly given priorities. Each student picks her most favorite topic from all topics that have not yet been taken by a student with higher priority. 

### Advantages:
  - It is incentive compatible for students to rank topics according to their true preferences. Students don't have to strategize.
  - Easy to explain and to understand.

### Disadvantages:
  - There is no way for students to express their cardinal preferences. Outcomes can be dominated by algorithms that allow to strategize but allow more effective risk allocation among students.
  - Students have to rank all seminars.

#. assign
##. title Optimal Assignment (OR)
